name: Deploy to AWS S3 & CloudFront

on:
  push:
    branches:
      - master # Triggers when you push to the main branch

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 4. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ensure this matches your bucket region

      # 5. Upload to S3
      - name: Deploy to S3
        run: |
          # Sync dist folder to S3, deleting old files that no longer exist
          aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete

      # 6. Invalidate CloudFront Cache (So updates show immediately)
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"